# This file is to configure the JSON paths from the AODN Data Services for indexing in Elasticsearch.
# https://github.com/aodn/data-services/blob/master/ARGO/oceancurrent/README.md#supporting-products

version: "0.4"
products:
  - product: "SST"
    description: "Sea Surface Temperature daily products"
    paths:
      - /STATE_daily/SST/SST.json
      - /STATE_daily/SST_ANOM/SST_ANOM.json
      - /STATE_daily/pctiles/pctiles.json
      - /DR_SST_daily/SST/SST.json
      - /DR_SST_daily/SST_ANOM/SST_ANOM.json
      - /DR_SST_daily/pctiles/pctiles.json

  - product: "SST 4 hour"
    description: "Sea Surface Temperature 4 hour products"
    paths:
      - /SST_4hr/SST/SST.json
      - /SST_4hr/SST_Filled/SST_Filled.json
      - /SST_4hr/SST_Age/SST_Age.json
      - /SST_4hr/Wind/Wind.json

  - product: "Current Meters"
    description: "Current Meters products including plots and time series"
    paths:
      - /timeseries/currentMetersCalendar-48.json
      - /timeseries/currentMetersCalendar-49.json
      - /timeseries/currentMetersRegion-48.json
      - /timeseries/currentMetersRegion-49.json
      - /timeseries/currentMetersPlot-48.json
      - /timeseries/currentMetersPlot-49.json

  - product: "Ocean Colour"
    description: "Ocean Colour products including chlorophyll-a concentration"
    paths:
      - /STATE_daily/CHL/CHL.json
      - /STATE_daily/CHL_AGE/CHL_AGE.json
      - /oceanColour-chlA.json
      - /oceanColour-chlA-year.json

  - product: "Adjusted Sea Level Anomaly"
    description: "Adjusted Sea Level Anomaly products"
    paths:
      - /STATE_daily/SLA/SLA.json
      - /STATE_daily/SLA_pctiles/SLA_pctiles.json

  - product: "Adjusted Sea Level Anomaly and Sea Surface Temperature"
    description: "Adjusted Sea Level Anomaly and Sea Surface Temperature products"
    paths:
      - /adjustedSeaLevelAnomaly-sst.json
      - /adjustedSeaLevelAnomaly-sst-year.json

  - product: "Tidal Currents"
    description: "Tidal Currents products"
    paths:
      - /tides/tidalCurrents-spd.json
      - /tides/tidalCurrents-sl.json

  - product: "SealCTD"
    description: "SealCTD products including temperature and salinity profiles"
    paths:
      - /AATAMS/sealCtd-sealTracks.json
      - /AATAMS/sealCtd-timeseriesSalinity.json
      - /AATAMS/sealCtd-timeseriesTemperature.json
      - /AATAMS/sealCtdTags-10days.json
      - /AATAMS/sealCtdTags-salinity.json
      - /AATAMS/sealCtdTags-temperature.json
      - /AATAMS/sealCtdTags-timeseries.json
      - /AATAMS/sealCtdTags-ts.json

  - product: "EAC Mooring Array"
    description: "EAC Mooring Array products SST for Brisbane only"
    paths:
      - /EAC_array_figures/EACMooringArray.json
