version: "0.1"
products:
  - product: "SST"
    description: "Sea Surface Temperature daily products"
    paths:
      - /STATE_daily/SST.json
      - /STATE_daily/SST_ANOM.json
      - /STATE_daily/pctiles.json

  - product: "SST 4 hour"
    description: "Sea Surface Temperature 4 hour products"
    paths:
      - /SST_4hr/SST.json
      - /SST_4hr/SST_Filled.json
      - /SST_4hr/SST_Age.json
      - /SST_4hr/Wind.json