version: "0.2"
products:
  - product: "SST"
    description: "Sea Surface Temperature daily products"
    paths:
      - /STATE_daily/SST/SST.json
      - /STATE_daily/SST_ANOM/SST_ANOM.json
      - /STATE_daily/pctiles/pctiles.json

  - product: "SST 4 hour"
    description: "Sea Surface Temperature 4 hour products"
    paths:
      - /SST_4hr/SST/SST.json
      - /SST_4hr/SST_Filled/SST_Filled.json
      - /SST_4hr/SST_Age/SST_Age.json
      - /SST_4hr/Wind/Wind.json

  - product: "Current Meters"
    description: "Current Meters products including plots and time series"
    paths:
      - /timeseries/ANMN_P48/ANMN_P48.json
      - /timeseries/ANMN_P49/ANMN_P49.json
