spring:
  config:
    import: optional:file:.env.dev[.properties]
  mvc:
    log-request-details: true
logging:
  level:
    root: info
    au.org.aodn.oceancurrent: debug

app:
  cors:
    allowed-origins:
      - "*"
    allowed-methods:
      - GET
      - OPTIONS
    allow-credentials: false
